---
remotes:
<<<<<<< HEAD
  primary: git@github.com:destructuring/ghp-layouts
  secondary: git@bitbucket.org:destructuring/ghp-layouts
  rb: https://github.com/destructuring/rb-helper
=======
  primary: git@github.com:destructuring/rb-helper
  secondary: git@bitbucket.org:destructuring/rb-helper
  sh: https://github.com/destructuring/jason
  bump: https://github.com/destructuring/mixin-bump
>>>>>>> rb/master
